version: '3.3'

services:
  web:
    image: azurefirst.azurecr.io/spree_shop:latest
    environment:
      REDIS_URL: redis://redis:6379/0
      DB_HOST: postgres
      DB_PORT: 5432
      WEBPACKER_DEV_SERVER_HOST: webpacker
      DISABLE_SPRING: 1
    depends_on:
      - postgres
      - redis
    ports:
      - 80:3000
    command: bundle exec puma -C config/puma.rb

  worker:
    image: azurefirst.azurecr.io/spree_shop:latest  
    environment:
      REDIS_URL: redis://redis:6379/0
      DB_HOST: postgres
      DB_PORT: 5432
      DISABLE_SPRING: 1
    depends_on:
      - postgres
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.0-alpine
    volumes:
      - redis:/data

volumes:
  redis:
  postgres:
