name: 'CI CD'

on:
  push:

env:
  REGISTRY_PATH: azurefirst.azurecr.io
  DOCKER_BUILKIT: 1
  DOCKER_IMAGE: azurefirst.azurecr.io/azurefirst-spree-store:${{ github.sha }}
  DEPLOYMENT: ${{ contains(github.ref, 'master') || contains(github.ref, 'staging') || contains(github.event.head_commit.message, 'force-deploy') }}

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-20.04
    if: ${{ !contains(github.event.head_commit.message, 'ci-skip') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_PATH }}
          username: azurefirst
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Image to Azure Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            azurefirst.azurecr.io/azurefirst-spree:latest
            ${{ env.DOCKER_IMAGE }}
          file: Dockerfile.production
